.github/workflows/release.yml
main.go

- The main.go was messed up during the rebase. Fixing it. 
- The repo used to be on the master branch, the github action needed to be changed to using main

Copy paste main over, Change github action to main branch

---

.github/workflows/test.yml

Add go build and go test to ci workflow as a PR check.

add unit test workflow

---

ios/lockdown_value.go
ios/utils.go
main.go

Fix issue #16 : incomplete deviceinfo 
Changed the info command to return the full response PLIST so it is guaranteed to have all the values.

Fix incomplete deviceinfo

---

ios/syslog/syslog.go

remove the leftover channel from the old go-ios

Remove unused channel

---

go.mod
go.sum
ios/pcap/pcap.go

ฅ՞•ﻌ•՞ฅ̊
ଳ ̊(•̀ᴗ•́)و
̑̑ վ'ᴗ' ի
( '▿ ' )
(๑‾ ꇴ ‾๑)
(๑ت๑)

add pcap file export and make it better

---

ios/deviceconnection.go

You can use it on windows when you have installed itunes.

add windows support

---

ios/debugproxy/debugproxy.go

change the permissions for the proxy daemon so all users can access it

change permission for usbmuxd proxy socket

---

ios/installationproxy/installationproxy.go
main.go

to address #76  this adds an uninstall command

Add uninstall command

---

npm_publish/postinstall.js

replace cp with copy

---

ios/imagemounter/imagedownloader.go

* This is meant to fix automatic image mounting on Windows OS  
* Added a check for the current OS to provide proper imageToFind string

Fix automatic image mounting on Windows

---

README.md
ios/mcinstall/mcinstall.go
ios/mcinstall/setproxy.go
main.go

You can now use:
for auth:
ios httpproxy 192.168.2.88 12345 user password --p12file=/Users/cert.p12 --password=a 
ios httpproxy 192.168.2.88 12345 --p12file=/Users/cert.p12 --password=a 
and 
ios httpproxy remove
to delete it again.

Add httpproxy command

---

ios/imagemounter/imagedownloader.go
ios/imagemounter/imagedownloader_test.go

the old repo wasn't well maintained and images were not working or deprecated. 
Using https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images now for the `image auto` command. 
Should resolve #167 
thanks a ton people!

Replace haikeu repo with mspvirajpatel

---

restapi/README.md
restapi/api/app_endpoints.go
restapi/api/routes.go

* Added endpoint for launching apps by provided bundle ID  
* Added endpoint for killing apps by provided bundle ID
* Updated swag docs

Add launch and kill endpoints

---

restapi/README.md
restapi/api/device_endpoints.go
restapi/api/routes.go
restapi/go.mod
restapi/go.sum

As requested advised to open the api project in different folder to start working on the api

few simple changes to restapi readme

---

npm_publish/postinstall.js

This command was deprecated with recent versions of npm.

remove npm bin command

---

ios/installationproxy/installationproxy.go
main.go

Hello this PR adds:
- the attribute "UIFileSharingEnabled" to the `apps` command
- an option (`--filesharing`) to the command `apps` which prints a list of all apps with the file sharing enabled

Add filesharing

---

restapi/api/device_endpoints.go
restapi/api/routes.go
restapi/api/streaming_endpoints.go

Adds capability to install and list developer images via api. 
Adds capability to receive notifications via api.

Improve api

---

ios/discover.go
main.go

We always tried to query devices on the network, but it's only needed when we start a tunnel. This is now only called in the function that starts the tunnel

query devices with MDNS only when required

---

ios/amfi/amfi.go
ios/imagemounter/imagemounter.go
main.go

Introduce capability to check current developer mode status or enable developer mode on a device  
All credit goes to [pymobiledevice3](https://github.com/doronz88/pymobiledevice3) and doronz88 for finding the way to do this

Developer mode

---

ios/tunnel/tunnel.go

If we send large datagrams over the QUIC connection we don't receive TCP acknowledgments from the device. Sending smaller packets over the tunnel solves this.

reduce the interface MTU so that large payloads are split up

---

ios/mcinstall/prepare.go

* Updated the skip keys for fresh device preparation according to the official Apple [docs](https://developer.apple.com/documentation/devicemanagement/skipkeys)

Update and reorder prepare skip keys

---

ios/appservice/appservice.go
ios/appservice/appservice_integration_test.go
ios/coredevice/coredevice.go

`appservice` package contains necessary code to launch apps on iOS 17.

Added appservice package

---

ios/appservice/appservice.go

this was somehow lost in refactoring

pass stdio identifiers

---

CONTRIBUTING.md

Fix some typos in CONTRIBUTING.md

---

ios/tunnel/tunnel_lockdown.go

the TUN interface often returned an error when an incomplete IPv6 packet was sent (one IPv6 packet + parts of the next one) sending one packet at a time resolved this issue

send one packet at a time for the lockdown tunnel

---

ios/imagemounter/imagedownloader.go
ios/utils.go
ios/zipconduit/zip_utils.go
ios/zipconduit/zipconduit_installer.go

- move unzip function to ios.Utils
- fix image auto command for 17+ with a deviceboxhq.com based download

Fix image auto command for ios17+

---

.github/workflows/release.yml
npm_publish/package.json
npm_publish/postinstall.js

Reverting last change for now.

Fix release pipeline

---

go.mod
go.sum
go.work.sum
ios/imagemounter/imagedownloader.go
ios/imagemounter/imagedownloader_test.go
ios/imagemounter/tss.go
ios/utils.go
ios/utils_test.go
main.go

Tss.go was not using the right proxy settings.

Fix proxy for image auto

---

ios/rsd.go
main.go

This PR adds methods and commands for listing RSD services from a device.

Allow listing rsd services

---

ios/instruments/instruments_deviceinfo.go

This PR fixes panics I came across due to an ignored error and and index out of range error.

Fix panic index out of range

---

ios/discover.go

I came across panics due to sends that might still happen after the channel has been close here. After investigation, it seems to me that it is perfectly safe to leave this channel oppened as, once it's no longer used, the garbage collector should clean it, as per [this SO](https://stackoverflow.com/a/8593986).
Now that I think of it, I wonder if it's to pass a channel with no capacity to the `checkEntry` goroutine since, should `FindDeviceInterfaceAddress` return, there would be nobody left to read what `checkEntry` could be trying to send, potentially leading to a leaking goroutine. Since there is no wait on it, the program still runs though.

Avoid panic due to sending on closed channel

---

ios/afc/fsync.go
ios/house_arrest/house_arrest.go
main.go

as i don't know how to add code to someone elses MR here is the cleanup for:
https://github.com/danielpaulus/go-ios/pull/280

Fsync container

---

README.md
main.go

Description
I've sorted alphabetically the command list in the help output and the readme file, for easier search and reading.

Updates to the documentation (alpha sorting and missing args)
