danielpaulus/go-ios

go-ios.go, usbmux/deviceconnection.go, usbmux/listen.go
Add Quick and Dirty support for the USBMux Listen command. 
When you use this command you will get a persistent connection that can be used to get notified about unplug or plug-in events for iOS devices. No need to use libusb or anything to discover new devices, usbmuxd does it for you :-D
=> Add listen command

ios/connect.go, ios/debugproxy/debugproxy.go, ios/deviceconnection.go, ios/forward/forward.go, ios/listdevices.go, ios/readpairrecord.go, ios/usbmuxconnection.go, ios/utils.go, main.go
Some parts of the code still execute a `log.Fatal` rather than returning an error. This is a leftover form my initial days of golang learning and now I think it is not a good idea for several reasons. 
This PR removes log.Fatal for deviceconnection.go and usbmuxconnection.go and replaces it with returning an error. 
I need those to return an actual error so I can try to reconnect in an endless loop for the `LISTEN` command rather than exitting and failing the command.
=> Change the listen command to run indefinitely and retry should usbmuxd be killed

ios/dtx_codec/connection.go
Previous code was causing compilation error due to lack of accessibility to error code being checked.
This is a workaround to check by the text of the error message instead lacking a cleaner solution.
=> Fix connection closed bug

ios/forward/forward.go
Current forward configuration listens only to request from localhost.
This change allows us to access to the forwarded port from other origins.
=> Change forward to listen on all interfaces

ios/lockdown_value.go
according to the raw plist, the type of TimeZoneOffsetFromUTC is real, and it should be umarshaled to float64, when declared  as int, the retrieved value will always be zero.
=> change TimeZoneOffsetFromUTC field of ios.AllValuesType from int to float64

.gitignore, ios/zipconduit/plists.go, ios/zipconduit/zip_utils.go, ios/zipconduit/zipconduit_installer.go, main.go
Adding app installation with streaming zip conduit. 
The cool thing is that this installation method can install uncompressed apps without compressing them to a zip first. 
Files will be sent to the device directly with no compression. 
You can install apps like so:
- for zipped ipa files: `ios install --path=/Users/user/wda.ipa --nojson`
- for uncompressed .app folders: `install --path=/Users/user/WebDriverAgentRunner-Runner.app --nojson`
=> App Installation using zip_conduit (like Xcode)

ios/utils.go, ios/zipconduit/zipconduit_installer.go
**Bug Description:**
When i try to install a ipa file, i find if META-INF folder is included in the unzip IPA package. The following error messages will be generated.
"**{"err":"mkdir /var/folders/3_/fjr0f3dn58j22061qts7sssh0000gp/T/prefix693025361/META-INF: file exists","level":"fatal","msg":"failed writing","time":"2021-07-25T20:16:11+08:00"}**“
Therefore, i added code determine whether the folder exists before creating it.
=> fix: META-INF file exists bug

README.md, ios/testmanagerd/xcuitestrunner.go, main.go
You can now specify args and env vars for WDA like:
`ios runwda --env ENV_1=something --env ENV_2=else --arg ARG1 --arg ARG2`
This resolves #51
=> add parameters for specifying wda args and env vars, update readme

.gitignore, ios/deviceconnection.go, ios/dtx_codec/channel.go, ios/dtx_codec/connection.go, ios/imagemounter/imagedownloader.go, ios/imagemounter/imagedownloader_test.go, ios/imagemounter/imagemounter.go, ios/listdevices_integration_test.go, ios/plistcodec.go, ios/reboot_listen_image_integration_test.go, ios/screenshotr/screenshot_integration_test.go, ios/syslog/syslog_integration_test.go, ios/testmanagerd/xcuitestrunner.go, ios/testmanagerd/xcuitestrunner_11.go, ios/testmanagerd/xcuitestrunner_test.go, ios/usbmuxconnection.go, ios/usbmuxconnection_test.go, ios/utils.go, ios/zipconduit/zipconduit_installer.go, main.go
- Hopefully fixes #85  #78  and #68 
- Adds support for iOS 11
- Some refactoring
- Adds an integration test for running webdriveragent
- move super verbose logs to trace level
- go-ios supports specifying a device udid with an env variable "udid" now
- tested everything on iOS 11.2.5, 13.6.1, 14.7.1 and 15.1.1
- DeviceConnection interface now returns an error as it should
- zipconduit installer can close the connection now
- added nice little unit test for auto dev image downloader
=> Adds XCTest integration test& multiple fixes to allow iOS 11 support and resolve bugs

ios/crypto_utils.go, ios/pair.go
- Exporting private keys was broken which caused other tools not being to able to use the device after pairing.
- cleaned up the certificate code a bit and added nice comments
Resolves #93
=> fix pairing

ios/diagnostics/diagnostics.go, ios/diagnostics/ioregistry.go, ios/diagnostics/mobilegestalt.go, ios/diagnostics/request.go
Signed-off-by: Ali Yousuf <aly.yousuf7@gmail.com>
This does 3 things:
- Move `MobileGestalt` to its own file to separate the concern, including its request payload.
- It removes sending `goodBye()` message request, otherwise you cannot reuse the Diagnostics connection to make another request. User can use `defer diagnosticsConn.Close()` to close the connection it manually.
- Adds query function for `IORegEntry` request from diagnostics, which returns very useful data, such as Battery information with `AppleSmartBattery` as `key`.
=> Add ability to make IORegEntry request

ios/testmanagerd/xcuitestrunner.go
startTestRunner12 does not set the XCTestConfigurationFilePath to a valid value when `--xctestconfig` is used with the `runwda` command. This leads to the following error
```
{"level":"info","msg":"2022-01-11 16:05:58.758140-0800 WebDriverAgentRunner-Runner[80932:41383367] Unable to load configuration data from specified path /; error: The file “System” couldn’t be opened because you don’t have permission to view it.\n","time":"2022-01-11T16:05:58-08:00"}
```
I was launching wda like so
```
$ ./go-ios runwda --udid=$udid --bundleid=com.apple.test.WebDriverAgentRunner-Runner --testrunnerbundleid=com.apple.test.WebDriverAgentRunner-Runner --xctestconfig=WebDriverAgentRunner.xctest
```
rather than using the default com.facebook.WebDriverAgentRunner bundle id.
This PR passes in the xctest …
=> pass the xctest config path for ios 14+

ios/testmanagerd/xcuitestrunner.go
The hack I introduced caused the xctest runner to fail with a weird error messages about the "PlugIns" directory. Works now. 
Fixes #43
=> Fix xctestconfig

README.md, ios/crypto_utils.go, ios/mcinstall/mcinstall.go, ios/pair.go, main.go
Allows to install configuration profiles generated by apple configurator, to set global http proxies, add wifi connections and do other cool things. 
`ios profile list` shows a list of all currently installed profiles, including identifier
`ios profile remove <profileIdentifier>` removes a profile from the device using its identifier. Example: `ios profile remove Daniels-MacBook-Pro-2.C10C60E6-94ED-4F50-B882-0D709A6103DF`
`ios profile add <profileFilePath>` adds the profile to the device unsupervised. That means you have to manually accept it on the device by going to the settings app. 
if your device is supervised though, you can use `ios profile add <profileFile> [--p12file=<orgid>] [--password=<p12password>]` and have all the profiles be silently installed to set advanced settings on …
=> Add support for profiles

ios/installationproxy/installationproxy.go, main.go
This commit adds a human-friendly line-per-process table output to the "ios ps" command, piggy-backing on the previously-unused --nojson option.  In order to actually fit on the screen, this does *not* print all of the fields available in the JSON, and also adds the app's bundle ID if available.   (This could add confusion given that the bundleID now appears *missing* from the json output.  I have at least noted this discrepancy in the "-help" output.  If desired, BundleID could be added to the JSON, or else the entire appInfo structure could be added as a nested field when available).
The JSON for "ps" returns an "IsApplication" flag, which is most likely usable for limiting output that is irrelevant to some users.  Rather than display "true/false" for IsApplication as an additional …
=> Add human-friendly ps output.  Add --all option to apps command.

ios/lockdown_language_locale.go
=> When setting device language, print language to debug log, not locale.

main.go
This commit also adds a "--system" option that allows built-in processes, such as com.apple.Maps, to be killed by bundleID.  (When specifying --pid or --process, there are no restrictions)
Examples of processes that one might want to kill this way:
com.apple.Maps   (using the --system option)
replayd          (when broadcast streaming becomes irrevocably hung)
assistivetouchd  (useful as a test.  If the AssistiveTouch home button is active, killing this makes the button briefly disappear, but it restarts automatically).
This commit attempts to preserve all previous behavior, but a few changes have been made:
* Some typos were corrected ("killd" -> "killed")
* Some spaces were added in log messages where variables were concatenated with no spaces
* The "kill" command now exits with a …
=> Add command-line option to kill processes by process-name or PID

ios/dtx_codec/connection.go, ios/instruments/instruments_channels.go, ios/instruments/metrics.go, ios/instruments/processcontrol.go, main.go
As the first step of adding the remaining instruments features, I added listening to device state notifications. 
`ios instruments notifications [options]` will start a JSON stream of notifications that indicate when applications are opened or closed on the device. Example: 
```
{"appName":"Phone","displayID":"com.apple.mobilephone","elevated_state":2,"elevated_state_description":"Background Task Suspended","execName":"/Applications/MobilePhone.app","mach_absolute_time":2163024584939,"pid":379,"state":2,"state_description":"Background Task Suspended","timestamp":{"Timestamp":"2022-08-02T22:38:20.739+02:00"}}
```
=> Implement CPU, Memory etc. profiling

ios/lockdown_assistivetouch.go, ios/lockdown_value.go, ios/utils.go, main.go
Using the same technique already used for querying and setting the device language and locale, go-ios can now enable and disable AssistiveTouch using the the magic boolean com.apple.Accessibility.AssistiveTouchEnabledByiTunes
This commit slightly modifies the existing SetValueForDomain() and related methods and structs to take an interface{} value (rather than a string) in order to pass a raw bool to lockdown.
This commit also replaces a few inconsistently used tabs in the verbose command-line "help" output.
Thank you to the team at alibaba/taobao-iphone-device (tidevice) for sharing the magic word to make this happen.
Validated on iPhone 5s, 6, 6s, 6s plus, 7, 8, se 1st gen, se 2nd gen, and 11 pro max.  iOS 11.4.1, 12.1, 12.5.5, 13.4, 13.6, 14.0.1, 14.7, 15.0, 15.3, and 16.0.1 beta. …
=> Add ability to enable/disable AssistiveTouch soft "home" button. iOS 11+

ios/instruments/helper.go, ios/instruments/instruments_deviceinfo.go, ios/instruments/instruments_notifications.go, main.go
I added two new fields to the info command. The response of hardwareInformation and networkInformation from the instruments service are now in the results if a developer image is mounted. 
hardWareInformation contains various cpu infos. Here is an example:
map[hwCPU64BitCapable:1 hwCPUsubtype:1 hwCPUtype:16777228 numberOfCpus:2 numberOfPhysicalCpus:2 speedOfCpus:0]
networkInformation contains a list of all network interfaces on the device. Example: 
map[en0:Wi-Fi en1:Ethernet Adaptor (en1) en2:Ethernet Adaptor (en2) lo0:Loopback pdp_ip0:Cellular (pdp_ip0)
pdp_ip1:Cellular (pdp_ip1) pdp_ip2:Cellular (pdp_ip2) pdp_ip3:Cellular (pdp_ip3) pdp_ip4:Cellular (pdp_ip4)]
Those are now part of the `ios info` command output only if the developer image was mounted on the device.
=> Add deviceinfo service info to info command

README.md
Quick typo fix in the `README` file
=> fix: correct form/from typo

ios/dtx_codec/connection.go
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19AzwRdqzwn13RkocrFYbYMaMMcbaCW8LU%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=USFGXaU)
If we try to build on armv7l we have this error : 
ios/dtx_codec/connection.go:174:31: cannot use 4294967295 (untyped int constant) as int value in argument to dtxConn.activeChannels.Store (overflows)
this fix this issue : #175
=> Fix build on armv7l

ios/forward/forward.go, main.go
Previous code has an out-of-order error check, starting a thread and *then* returning on error.  This leads to a null-pointer panic if you attempt to forward a port that is already in use.
=> Exit with error when attempting to forward an unavailable port.

ios/afc/afc.go, ios/afc/fsync.go, ios/utils.go, main.go
* [support list parameter when print apps](https://github.com/danielpaulus/go-ios/pull/165/commits/2db3aee41e77095fbc8df56b4b6357c086c06ac3)
```
go-ios apps --list
```
why do this?
now, every time we check the app list, it outputs a lot of information. But more often, we only care about the bundle ID, bundle name and version number. Therefore, adding a -- list parameter can clearly display the three information mentioned above.
* [support get disk space info](https://github.com/danielpaulus/go-ios/pull/165/commits/c45fe938fbfca286cece0e11bf06dc46e5152431)
```
go-ios diskspace
```
from this command, we can obtain the disk space information, including: total size, used szie, free size and block size.
like this :
=> support list parameter when print apps and add get disk space info cli

ios/simlocation/simlocation.go, restapi/api/device_endpoints.go, restapi/api/routes.go, restapi/api/util.go
* Added `GenericResponse` struct to have a single interface that can be used to return both errors and meaningful messages where applicable, instead of generating JSON on each spot with `gin.H` or whatever. If you are okay with this I can later update the existing functions
* Added endpoint to change the current device location by `latitude` and `longtitude` query params  
* Added endpoint to reset the device location to the actual one  
* Bubbled up an unhandled error in my own code for device location simulation
=> Add endpoints for changing device location

ios/dtx_codec/connection.go, ios/instruments/processcontrol.go, main.go
adds new --wait switch to keep the command running and display application logs when an app is launched with ios launch [bundleID]
=> Add --wait to ios launch

ios/screenshotr/mjpeg_server.go, main.go
start a simple mjpeg server by running
`ios screenshot --stream` on 0.0.0.0:3333. If you provide the port argument like so: 
`ios screenshot --stream --port=8082` the server will run on your specified port. Then watch a slow stream in your browser. 
This is only a fun feature or to use in debugging if all else fails. Screenshotr is too slow to be really useable on Retina/High Res devices because it sends huge PNG files. Those reach memory bandwith limits on the device. Also it is too unstable to be used in production scenarios. For useable mjpeg streams, use WebDriverAgent's built in server. 
On older devices, this works quite well though :-D
=> Add mjpeg server to screenshotr

ios/testmanagerd/xcuitestrunner.go, main.go
* Updated `runtest` command to accept 3 arguments so users can fine tune the test execution based on their own configuration - #224 
* Added `--bundle-id`, `test-runner-bundle-id` and `xctest-config` arguments to `runtest`  
* `test-runner-bundle-id` and `xctest-config` can be omitted which will use the initial logic of building them dynamically
=> Update runtest to accept additional arguments

ios/debugproxy/binforward.go, ios/debugproxy/debugproxy.go, ios/debugproxy/muxhandler.go, ios/deviceconnection.go, ios/listen.go, ios/usbmuxconnection.go, main.go
Support for `USBMUXD_SOCKET_ADDRESS` as recently introduced in [libusbmuxd](https://github.com/libimobiledevice/libusbmuxd#environment)
=> Support for USBMUXD_SOCKET_ADDRESS environment variable

ios/batterydiagnostics.go, main.go
Added support for domain "com.apple.mobile.battery"
(from libimobiledevice: `ideviceinfo -u {self.impl.device_udid} --domain com.apple.mobile.battery"`)
=> Added battery diagnostics domain

ios/afc/fsync.go, ios/deviceconnection.go, ios/dtx_codec/decoder.go, ios/dtx_codec/dtxprimitivedictionary.go, ios/listdevices.go, ios/lockdown.go, ios/pair_read.go, ios/usbmuxconnection_test.go
1. fix fsync fd > 256
2. close connection fd in ListDevices and ReadPair
3. return error when EnableSSL failed
4. export dtx.decodeAuxiliary for custom use
=> Fix fsync fd, fd leak and export some useful method

ios/lockdown_time_format.go, main.go
Added support to modify timeformat of an iOS device.
In lockdown, there is a key `Uses24HourClock` that returns values as true or false, when 24 Hour Clock is enabled or disabled, respectively.
Turns out this key's value can also be modified over Lockdown Connection, to enable or disable 24 Hour Clock on the device, in turn changing time format of the device.
=> Adding support to modify Time Format

ios/appservice/appservice.go, ios/appservice/appservice_integration_test.go, ios/xpc/connection.go, ios/xpc/encoding.go, main.go
There is no more process control service on iOS 17. The tasks of listing/killing processes is done via `com.apple.coredevice.appservice` now, as well as rebooting a device
=> Kill apps and reboot devices through appservice

ios/imagemounter/imagemounter.go, ios/imagemounter/personalized_image.go, ios/imagemounter/personalized_image_mounter.go, ios/imagemounter/tss.go, ios/imagemounter/tss_test.go, ios/plistcodec.go, main.go, restapi/api/device_endpoints.go
With iOS 17 we don't have developer disks per minor version that we can simply mount, we get "personalized" images where we have to ask apple for a signature first.
The cli command itself hasn't changed much, only the path to the image is now different. You need to mount the image at `~/Library/Developer/DeveloperDiskImages/iOS_DDI.dmg`, and then the path to `go-ios` should be like `/Volumes/Xcode_iOS_DDI_Personalized/Restore`. Pointing directly to `~/Library/Developer/DeveloperDiskImages/iOS_DDI.dmg` was not implemented as `dmg` files are not supported by the go std lib, and therefore to keep the implementation simpler.
=> Mount personalized developer disk images

ios/tunnel/pairrecord.go, ios/tunnel/pairrecord_test.go, ios/tunnel/untrusted.go, main.go
Remote pair records (the ones that are used in tunnel creation) are stored in the `/var/db/lockdown/RemotePairing/user_501` directory on MacOS. We now use the same structure as MacOS does so that we can reuse an already existing pairing created by MacOS.
=> Use same pair record structor as MacOS for remote pairing

ios/tunnel/tunnel.go, ios/tunnel/untrusted.go, main.go
With the blocking operation we could get the tunnel information only through logs.
Now we get back a `Tunnel` struct that has all relevant infos and it can be used to tear down the tunnel as well.
=> Make starting a tunnel a non-blocking operation

ios/forward/forward.go, main.go
Whenever the `go-ios` is used as a dependency package in any go project, it would be nice to use port forwarding feature with the possibility to free the listening port when the forwarding is stopped
- wrap the `net.Listener` in a dedicated struct
- provide the `Close()` function to free the listening port
- allow the eternal for loop in `connectionAccept` to break when `Close()` is called
- wrap any errors occurred
=> Allow closing listener in port forwarding

ios/imagemounter/tss.go
On linux hosts this fails with `Post "https://gs.apple.com/TSS/controller?action=2": tls: failed to verify certificate: x509: certificate signed by unknown authority` otherwise
=> Skip TLS certificate verification for getting the developer disk signature

ios/connect.go, ios/deviceconnection.go, ios/rsd.go, ios/syslog/syslog.go, ios/usbmuxconnection_test.go, ios/zipconduit/zipconduit_installer.go
Services that still work over usbmuxd on iOS 17 are also exposed as 'shim' services via RSD over the tunnel interface. With this change we transparently switch to using those services if available.
=> Use the shim service over the tunnel interface for zipconduit and syslog

ios/nskeyedarchiver/unarchiver.go, ios/testmanagerd/proxydispatcher.go
**Why?**
DTX message dispatcher has a lot of assumptions about received messages, all hard-coded. Unexpected payloads panic during decoding, which creates more problems for the users of the programmatic API.
**What is affected?**
No change in the runtime behavior of the happy path of message dispatcher. Unhappy paths now has errors.
**How was this fixed?**
We now utilize the `err` property under `TestListener` to report all decoder and message dispatcher errors in the test results.
=> Report proxy dispatcher panics under test listener

ios/tunnel/tunnel.go
the lower value caused the device to close the tunnel on iOS 17.4 beta
=> increase the number of random bytes sent before the parameter exchange

ios/http/http.go, ios/tunnel/untrusted.go
This changed in some minor version upgrade recently. Initially we always got back a public key from the device when we tried to verify the pairing. When this happened we skipped sending a pair-verify-failed message to the device. This case is now covered as well, and we a new pairing will be initiated.
Also, the http2 connection was hanging in this scenario because the device sent a `RST` frame to which we didn't react.
=> Fix creating a new device pairing

ios/imagemounter/personalized_image.go, ios/imagemounter/personalized_image_mounter.go, ios/imagemounter/tss.go
Sometimes the devices includes identifiers starting with 'Ap,' in the response from mobile_image_mounter. We need to copy those to the request to get the signature for the personalized developer disk image
=> Include missing personalization identifiers

ios/debugproxy/binforward.go, ios/instruments/helper.go, ios/instruments/location_simulation.go, ios/listdevices.go, main.go
The current `setlocation` only works for iOS below 17, the iOS 17 introduces a new instrumentation service `com.apple.instruments.dtservicehub` with the channel id `com.apple.instruments.server.services.LocationSimulation` for the simulated location.
By using DTX make a channel call:
- `imulateLocationWithLatitude:longitude:` with args to start the location simulation
- `stopLocationSimulation` to stop and clear the location simulation & data
The response payloads for both methods are `<nil>`
=> feat: Simulate location for iOS17

ios/dtx_codec/connection.go, ios/testmanagerd/xcuitestrunner.go, ios/testmanagerd/xcuitestrunner_11.go, ios/testmanagerd/xcuitestrunner_12.go, main.go
With this changes `ios runwda` will exit with error when WDA app dies (e.g. killed with `ios kill`, killed manually with AppSwitcher, or when iPhone is turned off).
`dtxConnection`'s `BreakdownCallback` is implemented with Functionals Options Pattern, so it's fully optional and shouldn't affect any other `dtxConnection` usages.
=> fix: quit runwda when wda dies

ios/testmanagerd/testlistener.go, ios/testmanagerd/testlistener_test.go
the close call happens in multiple places and we can not be sure that only one of those methods is getting called during an execution
=> ensure that the test listener channel gets closed only once

ios/dtx_codec/channel.go, ios/testmanagerd/testlistener.go
There was a memory leak when we handle fragmented DTX messages. The fragments were not completely cleaned up.
And in XCUITests the attachments were also retained completely, even though we were only using the string values of those attachments. Cloning those strings resolves this
=> fix memory leaks

ios/dtx_codec/connection.go
having it inside the loop destroys the reader after every iteration and it may contain bytes at that point
=> move initializing the buffered reader out of the loop

ios/testmanagerd/testlistener.go, ios/testmanagerd/xcuitestrunner.go
in most cases this is due to the test runner crashing (or it can also be closed manually through the UI)
=> set an error on the test run when we lose DTX connectivity

ios/tunnel/tunnel_api.go
This was a bug that made iOS18 use the old tunnel.
=> Fix version comparison

ios/imagemounter/imagedownloader.go, ios/imagemounter/tss.go, ios/mobileactivation/albert.go, main.go
In Golang only the default http client uses the system wide env var. this led to some weird behavior with half 
of go-ios supporting it and the other half not so much. I changed it to use the default transport always.
=> Fix proxy support

ios/imagemounter/imagemounter.go, ios/imagemounter/personalized_image_mounter.go, main.go
This PR adds an `unmount` sub-command to the `image` command for doing just that : unmounting currently mounted developer disk images, be them "standard" ones (iOS < 17) or personalized ones (iOS >= 17).
This PR is heavily inspired by [pymobiledevice3's implementation](https://github.com/doronz88/pymobiledevice3/blob/6351c9527e79a453228ce5969998d9e357b499f3/pymobiledevice3/services/mobile_image_mounter.py#L66-L80).
I wasn't sure whether I should include a `Hangup` command or not, like it's done with the mounting commands [here](https://github.com/danielpaulus/go-ios/blob/5403671c371d0d28e91997bf29f22c101368a423/ios/imagemounter/imagemounter.go#L95) and [here](https://github.com/danielpaulus/go-ios/blob/5403671c371d0d28e91997bf29f22c101368a423/ios/imagemounter/personalized_image_mounter.go# …
=> Allow unmounting disk images

ios/tunnel/tunnel_api.go
This PR adds a public method for removing a tunnel based on the serial number, basically bringing the recent `/tunnel` `DELETE` HTTP endpoint addition for use directly from go code importing `go-iOS`.
=> Allow removing tunnels from the tunnel manager

ios/tunnel/untrusted.go
I came across panics due to missing safety checks for accessing a map key and casting a variable. This PR doesn't prevent the situation(s) that caused the panics to happen, but it avoids the panics by returning errors.
=> Avoid panic due to interface conversion without check

main.go
This PR simply adds the ability to print WebDriverAgent's output to a file or stdout, just like the `runtest` command does.
=> Allow printing WebDriverAgent output from command line

main.go
* When trying to run a command while manually supplying `rsd-port` and `address` and using userspace tunnels, also the userspace tunnel port has to be supplied or it doesn't work
=> Add userspace port CLI option

main.go
This PR simply adds back the `image unmount` command introduced with #454 and remove by mistake with #464 [here](https://github.com/danielpaulus/go-ios/pull/464#discussion_r1724889745).
=> Add back the "image unmount" command removed by mistake

restapi/api/app_endpoints.go, restapi/api/routes.go
- app install through multipart form upload
- uninstall using the bundleid
=> Support app install and uninstall

ios/nskeyedarchiver/archiver_test.go, ios/nskeyedarchiver/objectivec_classes.go, ios/testmanagerd/xcuitestrunner.go, ios/testmanagerd/xcuitestrunner_11.go, ios/testmanagerd/xcuitestrunner_12.go
this value has changed with iOS 17. While this did not cause problems in most cases, UI interruption handlers were broken because of that. They simply stopped firing with that value pointing to the old path
=> fix 'automationFrameworkPath' for iOS 17+

ios/nskeyedarchiver/objectivec_classes.go, ios/testmanagerd/xcuitestrunner.go
When a popup (like a permission popup for the camera, notifications, etc) is shown before the XCUITest is started, the XCUITest runner will hang and after 30s we get the error `Failed to background test runner within 30.0s.`
By adding the option `"__ActivateSuspended": uint64(1),` when we launch the XCUITest (like Xcode does), this is not happening anymore.
Also, the `Error()` method of `NSError` was a bit too verbose. In the error that we got here, there is a entry `screenshot-data` in the `userInfo` dictionary, and we shouldn't include that in the error message (it's still stored in the error if someone really needs that)
=> Fix stuck XCUITest runner when a popup is shown on the screen

ios/instruments/processcontrol.go, main.go
iOS dictates a memory limit for apps and extensions. One of the extension is a Broadcast Extension with a limit of 50 MB. With the call `- (NSNumber *)requestDisableMemoryLimitsForPid:(int)arg1;` we could try to waive this limit as Xcode does this when view debugger is being attached.
=> Draft: Disable memory limit for pid

ios/connect.go, ios/listdevices.go, ios/tunnel/tunnel_api.go, main.go, restapi/api/middleware.go
by setting the host for tunnel info http api and tunnel sockets the go-ios client can run remotely. Main use case for me is using the devices connected to my mac inside docker desktop
=> allow setting custom tunnel host

ios/testmanagerd/xcuitestrunner.go
serializing the config makes changes to it and actually invalidates it
this fixes https://github.com/danielpaulus/go-ios/issues/512
=> revert reuse of xctestconfig

ios/startsession.go
Issue: When sending a `StartSession` request, we just check if there was an error reading the response message. However, we don't check if the response object itself contains an `Error` field.
Fix: Start checking for the `Error` field, and if present return an error accordingly.
=> Check for non-empty 'Error' string in 'StartSessionResponse'

main.go
The command parser expects `zoomtouch` as the command, but  in code we check for `zoom`
=> fix: zoom command

.github/workflows/release.yml
Mostly replicating what is done for macOS arm64 build; build with GOARCH flag and use `lipo` to build a fat binary. Needs a run in GH actions to confirm it's all working.
Fixes https://github.com/danielpaulus/go-ios/issues/318
=> builds: add linux-arm64 binary to the npm package

.github/workflows/release.yml
Due to https://github.com/konoui/lipo/issues/12 , we won't use `lipo` to build a fat binary. Instead, we'll copy the arch-specific ones into arch-specific folders that already exist.
=> builds: remove lipo command from linux build as it has issues with linux/amd64

npm_publish/postinstall.js
https://github.com/danielpaulus/go-ios/pull/529 now publishes binaries for both `linux/amd64` and `linux/arm64` but turns out the postinstallation scripts had two different architecture maps and one was missing `arm64`
=> postinstall: add arm64 as valid arch

ios/tunnel/tunnel_api.go
Currently the tunnel impl expects for ios < 17.4 an network interface on the host. Using userspace doesn't work here.
=> throw an error if userpsace tunnel is used for ios <17.4

ios/tunnel/userspace_tunnel.go
Keepaliveidle time should be set more aggresive than the gVisor's 2 hours default idle time. Many NAT and firewalls drop the idle connections more aggressively (30-60 secs apparently).
Keepaliveinterval option doesn't take affect as the keep alive probe doesn't start before the idle time reaches. It is 2 hours by default and before it reaches NAT/Firewall close the connection unlike kernel mode TUN device,
With this change the idle time will be more aggressive and according to several tests this fix connection drops. Long running test more than 24 hours achieved with this fix.
=> Set keepaliveidle time more aggressive against connection drops

ios/tunnel/tunnel_api.go, main.go
With this change ENABLE_GO_IOS_AGENT can be set to "user" or "kernel" to start selective mode tunnel.
=> Tunnel mode selection feature for agent mode.

ios/testmanagerd/proxydispatcher.go, ios/testmanagerd/xcuitestrunner.go
The `method` switch in proxydispatcher::Dispatch was missing a few cases, which led to missing XCUITest results when using go-ios on iOS <17 devices.
Additionally, the `productModuleName` field in the XCTestConfiguration appeared to be wrong (also for iOS <17 devices), leading to the same issue of missing test results. It has been changed to match the iOS 17 config, which seems to work better for the test cases I've tried.
=> Add missing proxydispatcher cases + fix productModuleName for iOS <17

ios/dtx_codec/connection.go
This log line generates a _lot_ of content, most of which doesn't seem to be terribly useful under most circumstances, e.g.
```
2025-01-17 03:48:28.389990-0500 <PROCESS_NAME> Got parameterized attribute fetch for XC_kAXXCParameterizedAttributeConvertHostedViewFrame response with values {
Height = "62.33333460489908";
Width = 74;
X = 354;
Y = 143;
}, error: (null)
```
This doesn't seem to happen for iOS 17, I've only observed it for iOS 16 so far. My guess is that for iOS 17 we use a different method that doesn't have this excessive logging (and that was likely an intentional change).
I'm changing it to "Debug", as it might be useful under specific circumstances, but I don't think it should print everything all the time.
=> Change noisy log line level from 'Info' to 'Debug'

ios/dtx_codec/connection.go
**DESCRIPTION**
When using a custom dispatcher for channel graphics messages, it appears that the `ResponseWithReturnValueInPayload` message type is returned periodically. However, the `func (g GlobalDispatcher) Dispatch(msg Message)` function currently only handles `UnknownTypeOne`. To properly receive GPU statistics, I had to modify the dispatcher to handle the `ResponseWithReturnValueInPayload` type as well, ensuring it is correctly passed into the Dispatch function.
Here's pseudocode for reference:
```Go
type mDispatcher struct {
}
func (md*mDispatcher ) Dispatch(msg dtx.Message) {
}
func (mp* mProvider)  InitializeWithDispatcher(device ios.DeviceEntry, msgDispatcher dtx.Dispatcher) error {
conn, err := connectInstruments(device)
conn.MessageDispatcher = msgDispatcher
channel := …
```
=> Allow ResponseWithReturnValueInPayload to be passed into dtxConnection.Dispatch

ios/testmanagerd/xctestrunnerutils_test.go, ios/testmanagerd/xctestrunutils.go
By introducing new methods and introducing a new metadata object to extract the version, the parsing becomes easier to read and extend in the future.
=> Refactor how xctestrun files are parsed

ios/diagnostics/request.go
I added some IORegistry values to the `batteryregistry` command, useful to parse the device battery conditions
=> Additional Battery IORegistry values

ios/testmanagerd/xcuitestrunner.go
This PR updates the StartXCTestWithConfig method to return a single error instead of []error. We now use errors.Join(targetErrors...) to aggregate multiple errors into one before returning.
=> Refactor StartXCTest Method to return errors.Join Instead of []error

ios/testmanagerd/testlistener.go, ios/testmanagerd/testlistener_test.go, ios/testmanagerd/xcuitestrunner_test.go
The PR fixes saving of in-progress tests reports that are interrupted when test runner is killed due to numerous reasons such as misuse of assertions in the unit test code.
With this PR, the report will preserver the important information about the test suite test results and provide an error line where the issue happens.
Before the fix
```
{"level":"info","msg":"Killing test runner with pid 948 ...","time":"2025-06-18T13:25:39+02:00"}
{"level":"info","msg":"Killing test runner with pid 948 ...","time":"2025-06-18T13:25:39+02:00"}
{"level":"info","msg":"Nothing to kill, process with pid 948 is already dead","time":"2025-06-18T13:25:39+02:00"}
{"level":"debug","msg":"Done running test","time":"2025-06-18T13:25:39+02:00"}
{"level":"debug","msg":"DTX Connection with …
```
=> Fix unsaved in progress reports

ios/testmanagerd/testlistener.go, ios/testmanagerd/testlistener_test.go
Current issue: go-ios incorrectly marks successful tests as failed, when test cases are inside test cases (BDD).
Xcode has no issues running them.
for testClass "HelloButton|ShowAlert" and  testMethod "GivenILaunchTheApp" the status with value "passed" is not being set.
t.runningTestSuite:
```go
*testmanagerd.TestSuite {Name: "ShowAlert", StartDate: time.Time(2025-07-01T18:35:28Z){wall: 0, ext: 63886991728, loc: *time.Location nil}, EndDate: time.Time(0001-01-01T00:00:00Z){wall: 0, ext: 0, loc: *time.Location nil}, TestDuration: gvisor.dev/gvisor/pkg/tcpip/stack.immediateDuration (0), TotalDuration: gvisor.dev/gvisor/pkg/tcpip/stack.immediateDuration (0), TestCases: []github.com/danielpaulus/go-ios/ios/testmanagerd.TestCase len: 1, cap: 1, …
```
=> Implemented BDD tests support

ios/accessibility/accessibility_control.go
**Problem:** 
`init` fails for AX service because deviceAllAuditCaseIDs returns `nil` as response for AuditCaseIDs.
**Solution:**
iOS `api >= 15`  has new method to fetch Audit IDs which is `deviceAllSupportedAuditTypes`. We are implementing this now based on api version.
Note: we need to silently fail `deviceHumanReadableDescriptionForAuditCaseID`  otherwise it blocks enabling AX.
=> Support new audit api for ios18
